### ISSUE TITLE
Do not panic if hornet startup takes a bit longer

### ISSUE THREAD

**Issue by muXxer** [iotaledger/inx-coordinator#58]
Right now the coordinator panics if the node bridge takes longer to connect.
In a network with a bigger database, hornet takes more time at bootup.
The coordinator should wait until hornet is ready, instead of crashing.

**Comment by alexsporn** [comment]
We do have some retries, but the whole idea is that the docker restart will make it start again automatically. Do you want to do busy waiting here? You can change the timeout and retry count, but there is not much we can do here without changing the whole app start flow

**Comment by muXxer** [comment]
The problem is that the coordinator in the private tangle setup has no automatic restart, and I guess thats for a reason :D

**Comment by luca-moser** [comment]
- This might not be a problem if the initial supply check is disabled on startup of the node
- Add a note to the wiki how to separately start the coordinator in case it failed to connect to the node in the private tangle setup

**Comment by alexsporn** [comment]
https://github.com/iotaledger/hornet/pull/1712
